# Generated by Django 4.0.4 on 2022-05-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
