# Generated by Django 4.0.4 on 2022-05-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_following_alter_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
