# Generated by Django 4.0.4 on 2022-05-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_likes_remove_post_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
